pipeline:
  name: Build python-pipeline-samples
  identifier: Build_jedicraft_python_pipeline_samples_1765928915213
  projectIdentifier: pythondemo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1755803134909
        repoName: jedicraft/python-pipeline-samples
        build: <+input>
